### ISSUE TITLE
Rotten Tomatoes integration not working

### ISSUE THREAD

**Issue by homeslice35** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#185] opened 2024-04-26 09:43 UTC
Hi,

The icon is not appearing on any rotten tomatoes movies or tv shows. I can see the icon on other pages such as IMDB and can see the context menu when I highlight text and right click. From inspecting the pages, I can see code relating to the addon on IMDB but not on rotten tomatoes, which could imply that it's not just hidden or missing but rather not loadin on rotten tomatoes.

To reproduce:

Fresh install on Firefox
Disable all other addons
Go to any rotten tomatoes movie/tv show page

OS: Windows
Browser: Firefox
Version: 125.0.2
Extension Version: 2.8.6

![RT](https://github.com/trossr32/sonarr-radarr-lidarr-autosearch-browser-extension/assets/163959057/5e2bd77c-acc6-4015-8c4e-be6a37383ebf)

![IMDB](https://github.com/trossr32/sonarr-radarr-lidarr-autosearch-browser-extension/assets/163959057/1741c4b9-b8c4-4857-a4b9-316196159f0a)

**Comment by trossr32** [comment] 2024-04-28 14:36
Caused by Rotten Tomatoes website redesign. Will be fixed in v2.8.7

**Closed** 2024-04-28 14:41 UTC
Labels: bug
